name: Python application build and test only

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install unittest2
        pip install mysql
        pip install mysql.connector
        pip install mock
        pip install fastapi
        pip install pydantic

    - uses: shogo82148/actions-setup-mysql@v1
      with:
        mysql-version: '8.0'
        my-cnf: |
          innodb_log_file_size=256MB
          innodb_buffer_pool_size=512MB
          max_allowed_packet=16MB
          max_connections=50
          local_infile=1
        root-password: ''
       
    -  name: run unittest
       run: |
        # calling via python will also add the current directory to sys.path
        cd app/
        python -m unittest test_service.py
